= Simpang Siur Kabar Internet
:author: Ari S. Diutri

== Sebuah Kesimpulan Penulis Tentang Informasi di Dunia Jaringan Internet

Internet... +
Mempertemukan berbagai bangsa, ras, dan kebudayaan yang ada di seluruh dunia. +
Mudahnya mendapatkan informasi saat sekarang hanya dengan mengetikkan kata kunci pada mesin pencari atau search engine.
//more

Internet.. +
Merupakan sebuah media dan alat. +
Memberikan kebebasan untuk berbagi dan menerima.

Informasi.. +
Dari berbagai macam bidang. Keilmuan, teknologi, budaya, kemanusiaan dan banyak lagi... yang disajikan melalui media dan alat yang bernama Internet ini. +
Banyak kemajuan, dan kadangkala kemunduran. :-) +
Banyak hal positif dan juga "negatif".

Informasi di internet... +
Banyak yang benar dan banyak yang salah. +
Garis batas antar baik, bagus dan benar dengan jahat, buruk dan salah sangat tipis. +
Kompleksnya isi atau content dari informasi yang beredar di internet menjadikan hal itu sangat mudah terjadi.

Adakah filter atau saringan terhadap konten-konten yang bersifat tidak benar? +
Ada, bahkan banyak. Tapi.... +
Sampai tulisan ini dibuat saya masih dengan keyakinan penuh menyatakan bahwa filter terbaik adalah "Diri Sendiri". +
Sadarilah kemampuan diri sendiri dalam memfilter informasi dari internet.

Saya belajar banyak hal dari internet, bahkan 70% pengetahuan yang saya punya adalah dari internet.
Sejauh yang saya dapatkan, pengetahuan tentang kemajuan teknologi adalah yang paling dominan, dan saya sangat mengandalkan internet untuk menggali jawaban untuk segala keingintahuan saya dalam bidang tersebut.

Tapi..., ada hal-hal yang sangat saya filter karna sadarnya saya akan keterbatasan diri sendiri, seperti:

> Informasi yang berhubungan dengan keyakinan, idealisme, agama, filosofi, prinsip hidup dan lain-lain yang "tidak kasat mata" yang berhubungan dengan hakikat keberadaan kita didunia ini.

Ini hanya berdasarkan pengalaman pribadi. Kekurang hati-hatian dalam mencari informasi tentang hal-hal tersebut diatas bisa "bikin nyasar".

Banyak informasi yang benar, dan banyak informasi yang salah tentang hal-hal itu. Menurut pendapat pribadi saya,  utamakan mencari informasi tentang hal-hal diatas di dunia nyata yang anda tau pasti sumbernya.

Kalau memang perlu mencari di Internet lacaklah sumber informasi itu terlebih dahulu sebelum ingin meyakininya. Pastikan mendapatkan informasi itu dari sumber yang bisa dipercaya.

Yuk..., filter diri sendiri dan orang-orang terdekat kita dalam mencari informasi di Internet!.

Sedikit himbauan untuk teman-teman yang suka berbagi informasi di Internet,

* Checklah sumber anda sebelum anda menyampaikannya kepada orang lain, karna anda ikut bertanggung jawab penuh dalam setiap informasi yang anda teruskan kepada orang tersebut.

* Internet hanyalah sebuah media dan alat, kitalah yang menentukan akan digunakan untuk positif atau negatif-kah media ini.

Itu jugalah yang mendasari keinginan saya berbagi informasi berdasarkan pengalaman.

Semoga bermanfaat. Mohon maaf sebelumnya jika terdapat kesalahan dalam kata-kata saya. Sesungguhnya itu datang dari keterbatasan saya sebagai manusia biasa.
