name: Deploy Jekyll Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Deploy to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_DEPLOY_DIR: ${{ secrets.VPS_DEPLOY_DIR }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -  /dev/null
          rsync -avz --delete _site/ $VPS_USER@$VPS_HOST:$VPS_DEPLOY_DIR
